# Generated by Django 4.0.6 on 2022-10-06 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('Information', models.CharField(max_length=256)),
                ('photo', models.FileField(blank=True, upload_to='Notifications/')),
                ('Action_required', models.CharField(max_length=256)),
                ('Action_taken', models.TextField(max_length=256)),
                ('Action_date', models.DateTimeField(auto_now=True)),
                ('Raised_by', models.CharField(max_length=256)),
                ('Status', models.CharField(blank=True, choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=256, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=256)),
                ('Resp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
