# Generated by Django 3.2.7 on 2022-06-10 17:39

from django.db import migrations, models
import django.db.models.deletion
import drawings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Model_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['model'],
            },
        ),
        migrations.CreateModel(
            name='Sub_Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_assembly', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Drawings_2D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Child_part', models.CharField(blank=True, max_length=256, null=True)),
                ('Drawing1', models.FileField(blank=True, null=True, upload_to=drawings.models.Drawings_2D.get_upload_path)),
                ('Drawing2', models.FileField(blank=True, null=True, upload_to=drawings.models.Drawings_2D.get_upload_path)),
                ('Photo1', models.FileField(blank=True, null=True, upload_to=drawings.models.Drawings_2D.get_upload_path)),
                ('Photo2', models.FileField(blank=True, null=True, upload_to=drawings.models.Drawings_2D.get_upload_path)),
                ('Process_Instructions', models.CharField(blank=True, help_text='optional', max_length=256, null=True)),
                ('Model_Name', models.ManyToManyField(blank=True, null=True, related_name='model_names', to='drawings.Model_Name')),
                ('Sub_Assembly_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drawings.sub_assembly')),
            ],
        ),
    ]
