# Generated by Django 3.2.7 on 2022-06-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Check_point1', models.CharField(max_length=256)),
                ('Check_point2', models.CharField(max_length=256)),
                ('Check_point3', models.CharField(max_length=256)),
                ('Check_point4', models.CharField(max_length=256)),
                ('Check_point5', models.CharField(max_length=256)),
                ('Check_point6', models.CharField(max_length=256)),
                ('Check_point7', models.CharField(max_length=256)),
                ('Check_point8', models.CharField(max_length=256)),
            ],
        ),
    ]
