# Generated by Django 4.0.6 on 2022-08-16 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0002_checksheet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckSheet',
        ),
    ]
